package com.jim.mybatis.model.po;

public class Author {
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column authors.id
	 *
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	private Long id;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column authors.name
	 *
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	private String name;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column authors.profile_id
	 *
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	private Long profileId;


	/**
	 *
	 */
	private Profile profile;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column authors.id
	 *
	 * @return the value of authors.id
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column authors.id
	 *
	 * @param id the value for authors.id
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column authors.name
	 *
	 * @return the value of authors.name
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column authors.name
	 *
	 * @param name the value for authors.name
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column authors.profile_id
	 *
	 * @return the value of authors.profile_id
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	public Long getProfileId() {
		return profileId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column authors.profile_id
	 *
	 * @param profileId the value for authors.profile_id
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	public void setProfileId(Long profileId) {
		this.profileId = profileId;
	}

	public Profile getProfile() {
		return profile;
	}

	public void setProfile(Profile profile) {
		this.profile = profile;
	}
}