package com.jim.mybatis.model.po;

import java.util.Date;

public class Link {
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column links.id
	 *
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	private Long id;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column links.book_id
	 *
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	private Long bookId;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column links.title
	 *
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	private String title;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column links.url
	 *
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	private String url;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column links.enabled
	 *
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	private String enabled;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column links.times
	 *
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	private Integer times;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column links.create_at
	 *
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	private Date createAt;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column links.update_at
	 *
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	private Date updateAt;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column links.id
	 *
	 * @return the value of links.id
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column links.id
	 *
	 * @param id the value for links.id
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column links.book_id
	 *
	 * @return the value of links.book_id
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	public Long getBookId() {
		return bookId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column links.book_id
	 *
	 * @param bookId the value for links.book_id
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	public void setBookId(Long bookId) {
		this.bookId = bookId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column links.title
	 *
	 * @return the value of links.title
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column links.title
	 *
	 * @param title the value for links.title
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column links.url
	 *
	 * @return the value of links.url
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column links.url
	 *
	 * @param url the value for links.url
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	public void setUrl(String url) {
		this.url = url == null ? null : url.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column links.enabled
	 *
	 * @return the value of links.enabled
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	public String getEnabled() {
		return enabled;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column links.enabled
	 *
	 * @param enabled the value for links.enabled
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	public void setEnabled(String enabled) {
		this.enabled = enabled == null ? null : enabled.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column links.times
	 *
	 * @return the value of links.times
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	public Integer getTimes() {
		return times;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column links.times
	 *
	 * @param times the value for links.times
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	public void setTimes(Integer times) {
		this.times = times;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column links.create_at
	 *
	 * @return the value of links.create_at
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	public Date getCreateAt() {
		return createAt;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column links.create_at
	 *
	 * @param createAt the value for links.create_at
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	public void setCreateAt(Date createAt) {
		this.createAt = createAt;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column links.update_at
	 *
	 * @return the value of links.update_at
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	public Date getUpdateAt() {
		return updateAt;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column links.update_at
	 *
	 * @param updateAt the value for links.update_at
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	public void setUpdateAt(Date updateAt) {
		this.updateAt = updateAt;
	}
}