package com.jim.mybatis.model.po;

import java.util.Date;

public class Profile {
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column profiles.id
	 *
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	private Long id;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column profiles.author_id
	 *
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	private Long authorId;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column profiles.blog
	 *
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	private String blog;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column profiles.create_at
	 *
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	private Date createAt;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column profiles.update_at
	 *
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	private Date updateAt;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column profiles.id
	 *
	 * @return the value of profiles.id
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column profiles.id
	 *
	 * @param id the value for profiles.id
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column profiles.author_id
	 *
	 * @return the value of profiles.author_id
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	public Long getAuthorId() {
		return authorId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column profiles.author_id
	 *
	 * @param authorId the value for profiles.author_id
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	public void setAuthorId(Long authorId) {
		this.authorId = authorId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column profiles.blog
	 *
	 * @return the value of profiles.blog
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	public String getBlog() {
		return blog;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column profiles.blog
	 *
	 * @param blog the value for profiles.blog
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	public void setBlog(String blog) {
		this.blog = blog == null ? null : blog.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column profiles.create_at
	 *
	 * @return the value of profiles.create_at
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	public Date getCreateAt() {
		return createAt;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column profiles.create_at
	 *
	 * @param createAt the value for profiles.create_at
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	public void setCreateAt(Date createAt) {
		this.createAt = createAt;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column profiles.update_at
	 *
	 * @return the value of profiles.update_at
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	public Date getUpdateAt() {
		return updateAt;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column profiles.update_at
	 *
	 * @param updateAt the value for profiles.update_at
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	public void setUpdateAt(Date updateAt) {
		this.updateAt = updateAt;
	}
}