package com.jim.mybatis.model.po;

public class ProfileWithBLOBs extends Profile {
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column profiles.description
	 *
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	private String description;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column profiles.avatar
	 *
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	private byte[] avatar;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column profiles.description
	 *
	 * @return the value of profiles.description
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column profiles.description
	 *
	 * @param description the value for profiles.description
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column profiles.avatar
	 *
	 * @return the value of profiles.avatar
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	public byte[] getAvatar() {
		return avatar;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column profiles.avatar
	 *
	 * @param avatar the value for profiles.avatar
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	public void setAvatar(byte[] avatar) {
		this.avatar = avatar;
	}
}