package com.jim.mybatis.model.po;

public class RolePrivilege {
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column role_privilege.role_id
	 *
	 * @mbggenerated Thu Sep 21 01:16:58 CST 2017
	 */
	private Long roleId;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column role_privilege.privilege_id
	 *
	 * @mbggenerated Thu Sep 21 01:16:58 CST 2017
	 */
	private Long privilegeId;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column role_privilege.role_id
	 *
	 * @return the value of role_privilege.role_id
	 * @mbggenerated Thu Sep 21 01:16:58 CST 2017
	 */
	public Long getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column role_privilege.role_id
	 *
	 * @param roleId the value for role_privilege.role_id
	 * @mbggenerated Thu Sep 21 01:16:58 CST 2017
	 */
	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column role_privilege.privilege_id
	 *
	 * @return the value of role_privilege.privilege_id
	 * @mbggenerated Thu Sep 21 01:16:58 CST 2017
	 */
	public Long getPrivilegeId() {
		return privilegeId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column role_privilege.privilege_id
	 *
	 * @param privilegeId the value for role_privilege.privilege_id
	 * @mbggenerated Thu Sep 21 01:16:58 CST 2017
	 */
	public void setPrivilegeId(Long privilegeId) {
		this.privilegeId = privilegeId;
	}
}