package com.jim.mybatis.model.po;

import java.util.Date;

public class User {
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column users.id
	 *
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	private Long id;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column users.username
	 *
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	private String username;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column users.email
	 *
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	private String email;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column users.password
	 *
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	private String password;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column users.salt
	 *
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	private String salt;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column users.create_at
	 *
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	private Date createAt;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column users.update_at
	 *
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	private Date updateAt;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column users.avatar
	 *
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	private byte[] avatar;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column users.id
	 *
	 * @return the value of users.id
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column users.id
	 *
	 * @param id the value for users.id
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column users.username
	 *
	 * @return the value of users.username
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column users.username
	 *
	 * @param username the value for users.username
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	public void setUsername(String username) {
		this.username = username == null ? null : username.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column users.email
	 *
	 * @return the value of users.email
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column users.email
	 *
	 * @param email the value for users.email
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column users.password
	 *
	 * @return the value of users.password
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column users.password
	 *
	 * @param password the value for users.password
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column users.salt
	 *
	 * @return the value of users.salt
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	public String getSalt() {
		return salt;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column users.salt
	 *
	 * @param salt the value for users.salt
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	public void setSalt(String salt) {
		this.salt = salt == null ? null : salt.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column users.create_at
	 *
	 * @return the value of users.create_at
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	public Date getCreateAt() {
		return createAt;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column users.create_at
	 *
	 * @param createAt the value for users.create_at
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	public void setCreateAt(Date createAt) {
		this.createAt = createAt;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column users.update_at
	 *
	 * @return the value of users.update_at
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	public Date getUpdateAt() {
		return updateAt;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column users.update_at
	 *
	 * @param updateAt the value for users.update_at
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	public void setUpdateAt(Date updateAt) {
		this.updateAt = updateAt;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column users.avatar
	 *
	 * @return the value of users.avatar
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	public byte[] getAvatar() {
		return avatar;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column users.avatar
	 *
	 * @param avatar the value for users.avatar
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	public void setAvatar(byte[] avatar) {
		this.avatar = avatar;
	}
}