package com.jim.mybatis.model.po;

public class UserRole {
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column user_role.user_id
	 *
	 * @mbggenerated Thu Sep 21 01:16:58 CST 2017
	 */
	private Long userId;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column user_role.role_id
	 *
	 * @mbggenerated Thu Sep 21 01:16:58 CST 2017
	 */
	private Long roleId;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column user_role.user_id
	 *
	 * @return the value of user_role.user_id
	 * @mbggenerated Thu Sep 21 01:16:58 CST 2017
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column user_role.user_id
	 *
	 * @param userId the value for user_role.user_id
	 * @mbggenerated Thu Sep 21 01:16:58 CST 2017
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column user_role.role_id
	 *
	 * @return the value of user_role.role_id
	 * @mbggenerated Thu Sep 21 01:16:58 CST 2017
	 */
	public Long getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column user_role.role_id
	 *
	 * @param roleId the value for user_role.role_id
	 * @mbggenerated Thu Sep 21 01:16:58 CST 2017
	 */
	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}
}