package com.jim.mybatis.model.entities;

import java.util.Date;

public class Privilege {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column privileges.id
     *
     * @mbggenerated Thu Sep 21 01:16:58 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column privileges.name
     *
     * @mbggenerated Thu Sep 21 01:16:58 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column privileges.uri
     *
     * @mbggenerated Thu Sep 21 01:16:58 CST 2017
     */
    private String uri;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column privileges.create_at
     *
     * @mbggenerated Thu Sep 21 01:16:58 CST 2017
     */
    private Date createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column privileges.update_at
     *
     * @mbggenerated Thu Sep 21 01:16:58 CST 2017
     */
    private Date updateAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column privileges.id
     *
     * @return the value of privileges.id
     *
     * @mbggenerated Thu Sep 21 01:16:58 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column privileges.id
     *
     * @param id the value for privileges.id
     *
     * @mbggenerated Thu Sep 21 01:16:58 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column privileges.name
     *
     * @return the value of privileges.name
     *
     * @mbggenerated Thu Sep 21 01:16:58 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column privileges.name
     *
     * @param name the value for privileges.name
     *
     * @mbggenerated Thu Sep 21 01:16:58 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column privileges.uri
     *
     * @return the value of privileges.uri
     *
     * @mbggenerated Thu Sep 21 01:16:58 CST 2017
     */
    public String getUri() {
        return uri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column privileges.uri
     *
     * @param uri the value for privileges.uri
     *
     * @mbggenerated Thu Sep 21 01:16:58 CST 2017
     */
    public void setUri(String uri) {
        this.uri = uri == null ? null : uri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column privileges.create_at
     *
     * @return the value of privileges.create_at
     *
     * @mbggenerated Thu Sep 21 01:16:58 CST 2017
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column privileges.create_at
     *
     * @param createAt the value for privileges.create_at
     *
     * @mbggenerated Thu Sep 21 01:16:58 CST 2017
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column privileges.update_at
     *
     * @return the value of privileges.update_at
     *
     * @mbggenerated Thu Sep 21 01:16:58 CST 2017
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column privileges.update_at
     *
     * @param updateAt the value for privileges.update_at
     *
     * @mbggenerated Thu Sep 21 01:16:58 CST 2017
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }
}