package com.jim.mybatis.model.mapper;

import com.jim.mybatis.model.po.Author;

public interface AuthorMapper {
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table authors
	 *
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table authors
	 *
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	int insert(Author record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table authors
	 *
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	int insertSelective(Author record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table authors
	 *
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	Author selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table authors
	 *
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	int updateByPrimaryKeySelective(Author record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table authors
	 *
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	int updateByPrimaryKey(Author record);
}