package com.jim.mybatis.model.mapper;

import com.jim.mybatis.model.po.Comment;

public interface CommentMapper {
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table comments
	 *
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table comments
	 *
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	int insert(Comment record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table comments
	 *
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	int insertSelective(Comment record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table comments
	 *
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	Comment selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table comments
	 *
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	int updateByPrimaryKeySelective(Comment record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table comments
	 *
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	int updateByPrimaryKeyWithBLOBs(Comment record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table comments
	 *
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	int updateByPrimaryKey(Comment record);
}