package com.jim.mybatis.model.mapper;

import com.jim.mybatis.model.po.Link;

import java.util.List;

public interface LinkMapper {

	List<Link> linksForBookDownload(Long bookId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table links
	 *
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table links
	 *
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	int insert(Link record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table links
	 *
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	int insertSelective(Link record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table links
	 *
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	Link selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table links
	 *
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	int updateByPrimaryKeySelective(Link record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table links
	 *
	 * @mbggenerated Sun Sep 24 01:38:32 CST 2017
	 */
	int updateByPrimaryKey(Link record);
}