package com.jim.mybatis.model.mapper;

import com.jim.mybatis.model.entities.Privilege;

public interface PrivilegeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privileges
     *
     * @mbggenerated Thu Sep 21 01:16:58 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privileges
     *
     * @mbggenerated Thu Sep 21 01:16:58 CST 2017
     */
    int insert(Privilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privileges
     *
     * @mbggenerated Thu Sep 21 01:16:58 CST 2017
     */
    int insertSelective(Privilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privileges
     *
     * @mbggenerated Thu Sep 21 01:16:58 CST 2017
     */
    Privilege selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privileges
     *
     * @mbggenerated Thu Sep 21 01:16:58 CST 2017
     */
    int updateByPrimaryKeySelective(Privilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privileges
     *
     * @mbggenerated Thu Sep 21 01:16:58 CST 2017
     */
    int updateByPrimaryKey(Privilege record);
}