package com.jim.mybatis.model.mapper;

import com.jim.mybatis.model.entities.UserRole;

public interface UserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Thu Sep 21 01:16:58 CST 2017
     */
    int insert(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Thu Sep 21 01:16:58 CST 2017
     */
    int insertSelective(UserRole record);
}